### ISSUE TITLE
persistent ESB volume for etcd

### ISSUE THREAD

**Issue by rimusz** [juju-solutions/bundle-kubernetes-core#36] opened 2016-11-08 16:15 UTC
etcd unit should have a persistent ESB volume, that should allow easier to recover etcd if VM reboots.

Core bundle is very handy for dev/test cluster, so persistent volume for etcd would be nice to have.

**Comment by ktamiola** [comment] 2016-11-11 15:58
Very good point. VM shutdown messes up the whole setup!

**Comment by marcoceppi** [comment] 2016-11-11 16:46
Closing as duplicate of https://github.com/juju-solutions/bundle-canonical-kubernetes/issues/127 Once that's updated, since the etcd in both bundles is the same charm, it'll be reflected here.

**Closed by marcoceppi** 2016-11-11 16:46 UTC

**Comment by ktamiola** [comment] 2016-11-11 16:47
@marcoceppi Thank you!
